apiVersion: v1.wannabe.dev/v1
kind: AdaptiveWorkflow
metadata:
  name: linear-workflow
spec:
  optimizationGoal: MinimizeTime
  maxResources:
    cpu: "1"
    memory: "512Mi"
  tasks:
    - name: step-1
      image: alpine:latest
      command: ["echo", "Starting Step 1"]
    
    - name: step-2
      image: alpine:latest
      command: ["echo", "Starting Step 2"]
      dependencies: ["step-1"]
      
    - name: step-3
      image: alpine:latest
      command: ["echo", "Finalizing Step 3"]
      dependencies: ["step-2"]
